version: "3.3"  
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: root
    environment: 
        - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"